[package]
name = "wasmchat"
version = "0.1.0"
authors = ["Aaron McLeod <aaron.g.mcleod@gmail.com>"]
edition = "2018"

[dependencies]
web_logger = "0.1"
log = "0.4"
strum = "0.9"
strum_macros = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
stdweb = "0.4.8"
yew = "0.4.0"
